### ISSUE TITLE
Output html explanation

### ISSUE THREAD

**Issue by selfrefactor** [legraphista/stresser#2]
Can you provide with a simple explanation what the output data actually means? I made a guess for half of the things, but still I find it not self-explanatory.

**Comment by legraphista** [comment]
Yes, I was planning to do a proper Readme, but I couldn't find the time. I'll have it updated today.

**Comment by selfrefactor** [comment]
Thanks, dude! You are fast.

**Comment by legraphista** [comment]
@selfrefactor The readme file has been updated with a proper explanation of the output. If there is something that I missed / is not clear, feel free to reopen to issue and I'll do my best to explain it.

Thanks,
 Stefan
