### ISSUE TITLE
How to run a URL with parameters

### ISSUE THREAD

**Issue by sanchezzzhak** [legraphista/stresser#3]
How to run a URL with parameters?

sample

> http://localhost:3000/slug_test/?id=1&streamid=123123

`stresser http://localhost:3000/slug_test/?id=1&streamid=12121212 -c 10000 -n 10 -t 20000 --html=/home/reports/report-$(date +%s).html --threads=16 --force`

first get argument "id" is okay, "streamid" argument is not found

`````` js
var url = require('url');
var finalhandler = require('finalhandler');
var http = require('http');
var Router = require('router');

var routerOpts = {}, router = Router(routerOpts);
var server = http.createServer(function onRequest(req, res) {
     router(req, res, finalhandler(req, res))
});

router.get('/slug_test', function(req,res){
     var queryData = url.parse(req.url, true).query;
     console.log('queryData',queryData );
     console.log('url', req.url);
});
server.listen(3000)
`

console
``` queryData { id: '1' }
url /slug_test/?id=1`
``````

**Comment by legraphista** [comment]
Hey @sanchezzzhak,
`&` is a special terminal symbol.
Going back to basics, trying `curl http://localhost:3000/slug_test/?id=1&streamid=12121212` would only yield 

```
queryData { id: '1' }
url /slug_test/?id=1
```

but `curl "http://localhost:3000/slug_test/?id=1&streamid=12121212"` will give the correct result 

```
queryData { id: '1', streamid: '123123' }
url /slug_test/?id=1&streamid=123123
```

So the command should be `stresser "http://localhost:3000/slug_test/?id=1&streamid=12121212" -c 10000 -n 10 -t 20000 --html=/home/reports/report-$(date +%s).html --threads=16 --force`

Hope it helps,
~ Stefan
